apiVersion: batch/v1
kind: Job
metadata:
  namespace: kube-system
  name: unlabelnode
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 30
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: unlabelnode-job
        env:
            - name: KUBE_VERSION
              value: "v1.18.3"
        image: "tapassharma/kubectl"
        args: ['label','nodes','--all','tapas/sharma-']
